piVersion: apps/v1
kind: Deployment
metadata:
  name: leumi-deployment
spec:
  selector:
    matchLabels:
      app: leumi-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
	app: leumi-app
    spec:
      containers:
      - name: leumi-app
        image: 811073997600.dkr.ecr.eu-central-1.amazonaws.com/jenkins:latest
        ports:
	- containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leumi-service
spec:
  type: LoadBalancer
  selector:
    app: leumi-app
  ports:
        - targetPort: 3000
          port: 443



